version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Stockholm
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: html-proofer
    versions:
    - 3.18.5
    - 3.18.6
    - 3.18.8
    - 3.19.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: activesupport
    versions:
    - 5.2.4.4
    - 5.2.4.5
  - dependency-name: fastimage
    versions:
    - 2.2.1
    - 2.2.2
  - dependency-name: jekyll
    versions:
    - 3.9.0
